#include "src/game/envfx_snow.h"

const GeoLayout clone_luigi_luigi_head_no_hat[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_002_switch_option_head_000_displaylist_head_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_luigi_luigi_left_hand_holding[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, clone_luigi_002_switch_option_left_hand_002_offset_left_hand_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_luigi_luigi_right_hand_holding[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, clone_luigi_002_switch_option_right_hand_holding_002_offset_right_hand_holding_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_luigi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 181, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 24576),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_luigi_000_offset_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_offset_001_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 0, 0, clone_luigi_000_offset_001_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_displaylist_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, clone_luigi_luigi_head_no_hat),
										GEO_CLOSE_NODE(),
										GEO_ASM(0, geo_mario_head_rotation),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -6, 46, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_luigi_000_offset_003_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_offset_004_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, clone_luigi_000_offset_004_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_cosmic_clone_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_cosmic_clone_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_displaylist_003_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, clone_luigi_luigi_left_hand_holding),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -6, -46, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_luigi_000_offset_006_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_offset_007_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, clone_luigi_000_offset_007_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_cosmic_clone_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_cosmic_clone_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_displaylist_004_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, clone_luigi_luigi_right_hand_holding),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -5, 30, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_luigi_000_offset_009_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_offset_010_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, clone_luigi_000_offset_010_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, clone_luigi_000_offset_011_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -5, -30, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_luigi_000_offset_012_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_offset_013_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, clone_luigi_000_offset_013_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_cosmic_clone_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_luigi_000_displaylist_005_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
