#include "src/game/envfx_snow.h"

const GeoLayout clone_mario_002_switch_opt0_000_switch_cap_on_off_opt1_Switch_eyes_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_007_switch_option_007_displaylist_mesh_layer_1_mat_override_Eyes_Half_Open_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_mario_002_switch_opt0_000_switch_cap_on_off_opt1_Switch_eyes_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_007_switch_option_007_displaylist_mesh_layer_1_mat_override_Eyes_Closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_mario_002_switch_opt0_000_switch_cap_on_off_opt1_Switch_eyes_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_007_switch_option_007_displaylist_mesh_layer_1_mat_override_Eyes_Dead_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_mario_no_hat[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_007_switch_option_007_displaylist_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, clone_mario_002_switch_opt0_000_switch_cap_on_off_opt1_Switch_eyes_opt1),
			GEO_BRANCH(1, clone_mario_002_switch_opt0_000_switch_cap_on_off_opt1_Switch_eyes_opt2),
			GEO_BRANCH(1, clone_mario_002_switch_opt0_000_switch_cap_on_off_opt1_Switch_eyes_opt3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_mario_hand_left_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, clone_mario_002_switch_option_002_offset_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_mario_hand_right_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, clone_mario_002_switch_option_002_offset_02_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout clone_mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_mario_000_offset_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_offset_001_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, clone_mario_000_offset_001_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_displaylist_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, clone_mario_no_hat),
										GEO_CLOSE_NODE(),
										GEO_ASM(0, geo_mario_head_rotation),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_mario_000_offset_003_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_offset_004_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, clone_mario_000_offset_004_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_cosmic_clone_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_cosmic_clone_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_displaylist_003_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, clone_mario_hand_left_open),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_mario_000_offset_006_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_offset_007_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, clone_mario_000_offset_007_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_cosmic_clone_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_cosmic_clone_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_displaylist_004_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, clone_mario_hand_right_open),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_mario_000_offset_009_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_offset_010_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, clone_mario_000_offset_010_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, clone_mario_000_offset_011_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clone_mario_000_offset_012_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_offset_013_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, clone_mario_000_offset_013_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_cosmic_clone_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, clone_mario_000_displaylist_005_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
